const DECK = [
  { pergunta: "Matt",
    resposta: "Não sabotar minha felicidade ficando apx por comprometidas",
  },
  { pergunta: "Joyce",
    resposta: "Passar pelo final de semana sem mandar mensagem para ex",
  },
  { pergunta: "Mari",
    resposta: "Não trocar os migos do Moon Gang pelo B41xar14 Bléh",
  },
/*   { pergunta: "André",
    resposta: "Perceber que a Joyce é o amor da minha vida",
  }, */
  {
    pergunta: "André",
    resposta: "Beber água / não dar pt nas festinias *proerd*",
  },
  { pergunta: "Apolinario",
    resposta: "Não esquecer meu guarda-chuva para a festa",
  },
  { pergunta: "Chris",
    resposta: "Passar 1 dia sem arranjar treta",
  },
  { pergunta: "Matt",
    resposta: "é aNNya",
  },
  { pergunta: "Joyce",
    resposta: "Meditation for not to kick somebody's ass today",
  },
  { pergunta: "Gabriel",
    resposta: "Exercitar o perdão S2 *abraço coletivo*",
  },
  { pergunta: "Abdullay",
    resposta: "é gaRota* (e não 'gaRRota') haha",
  },
  { pergunta: "Abdullay",
    resposta: "Protect my girlfriend from Joyce",
  },
  { pergunta: "Mari",
    resposta: "Pensar se vou dar uma chance para o Matt"
  },
  { pergunta: "Annya",
    resposta: "Buy my ticket to Brazil",
  },
  { pergunta: "Apolinario",
    resposta: "No smoking pendrive",
  },
  { pergunta: "Chris",
    resposta: "Assistir Friends",
  },
  { pergunta: "Gabriel",
    resposta: "Lançar música nova para os meus fãs",
  },
]

/* const DECK = [
    { pergunta: "O que é JSX?", 
      resposta: "Uma extensão de linguagem do JavaScript",
    },
    { pergunta: "O React é __",
      resposta: "Uma biblioteca JavaScript para construção de interfaces",
    },
    { pergunta: "Componentes devem iniciar com __",
      resposta: "Letra maiúscula",
    },
    { pergunta: "Podemos colocar __ dentro do JSX",
      resposta: "Expressões",
    },
    { pergunta: "O ReactDOM nos ajuda __",
      resposta: "Interagindo com a DOM para colocar componentes React na tela",
    },
    { pergunta: "Usamos o npm para __",
      resposta: "Gerenciar os pacotes necessários e suas dependências",
    },
    { pergunta: "Usamos o props para __",
      resposta: "Passar diferentes informações para componentes",
    },
    { pergunta: "Usamos estado (state) para __",
      resposta: "Dizer para o React quais informações quando atualizadas devem renderizar a tela novamente",
    }
] */

export default DECK;