const DECK = [
  { pergunta: "Matt",
    resposta: "Não sabotar minha felicidade ficando apx por comprometidas",
  },
  { pergunta: "Joyce",
    resposta: "Passar pelo final de semana sem mandar mensagem para ex",
  },
  { pergunta: "Mari",
    resposta: "Não trocar os migos do Moon Gang pelo B41xar14 Bléh",
  },
  { pergunta: "André",
    resposta: "Nunca deixar a Joy no vácuo pq ela fica pistola </3",
  },
  { pergunta: "Apolinario",
    resposta: "Não esquecer meu guarda-chuva para a festa",
  },
  { pergunta: "Chris",
    resposta: "Passar 1 dia sem arranjar treta",
  },
  { pergunta: "Mari",
    resposta: "Ajudar a Day nos projetos de React"
  },
  { pergunta: "Matt",
    resposta: "é aNNya",
  },
  { pergunta: "Gabriel",
    resposta: "Exercitar o perdão S2 *abraço coletivo*",
  },
  { pergunta: "Abdullay",
    resposta: "Não é gaRRota, é gaRota haha",
  },
  { pergunta: "Annya",
    resposta: "Comprar minha passagem para o Brasil",
  },
  { pergunta: "Apolinario",
    resposta: "No smoking pendrive",
  },
  { pergunta: "Chris",
    resposta: "Assistir Friends",
  },
  { pergunta: "Gabriel",
    resposta: "Lançar música nova para os meus fãs",
  },
]

/* const DECK = [
    { pergunta: "O que é JSX?", 
      resposta: "Uma extensão de linguagem do JavaScript",
    },
    { pergunta: "O React é __",
      resposta: "Uma biblioteca JavaScript para construção de interfaces",
    },
    { pergunta: "Componentes devem iniciar com __",
      resposta: "Letra maiúscula",
    },
    { pergunta: "Podemos colocar __ dentro do JSX",
      resposta: "Expressões",
    },
    { pergunta: "O ReactDOM nos ajuda __",
      resposta: "Interagindo com a DOM para colocar componentes React na tela",
    },
    { pergunta: "Usamos o npm para __",
      resposta: "Gerenciar os pacotes necessários e suas dependências",
    },
    { pergunta: "Usamos o props para __",
      resposta: "Passar diferentes informações para componentes",
    },
    { pergunta: "Usamos estado (state) para __",
      resposta: "Dizer para o React quais informações quando atualizadas devem renderizar a tela novamente",
    }
] */

export default DECK;